### ISSUE TITLE
MyNewAgent example in README.md uses faulty signature

### ISSUE THREAD

**Issue by pdeibert** [jw3il/pomcpp2#1]
The example of defining a new agent `MyNewAgent` as shown in `README.md` tries to override `bboard::Move act(const bboard::State* state)`, but does not compile since `bboard::Agent` declares the signature as `Move act(const Observation* obs)`. I'm assuming the argument type in the example should be changed to `const Observation* obs` instead.

**Comment by jw3il** [comment]
Good find, thank you! I have updated the README accordingly (see 89ce2803a1ff5009d852b5642cf1b6fcaca90ab6).
